//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bil
    {
        public System.Guid Id { get; set; }
        public System.Guid FK_Appointment { get; set; }
        public double Final_Price { get; set; }
        public string Number { get; set; }
    
        public virtual Appointment Appointment { get; set; }
    }
}
